### ISSUE TITLE
The prior distribution of z

### ISSUE THREAD

**Issue by GilgameshD** [ronaldiscool/VAETutorial#1]
In the function of importance_sampling, your code is:

logpz = gaussian_log_prob(z, torch.zeros(z.shape).cuda(), torch.zeros(z.shape).cuda())

should the var be torch.ones(z.shape) ?

**Comment by ronaldiscool** [comment]
The function consumes the log of the variance, which should be 0.

**Comment by GilgameshD** [comment]
I see, Thanks!
